# Generated by Django 2.0.8 on 2018-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('son_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество')),
                ('user_company', models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания')),
                ('category', models.IntegerField(choices=[(1, 'Администратор'), (2, 'Сотрудник'), (3, 'Участник')], db_index=True, default=3, verbose_name='Категория')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('url_company', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
