# Generated by Django 2.0.8 on 2018-10-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20181007_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='usercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='userprofile.UserCategory'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('slug', 'parent')},
        ),
    ]
