# Generated by Django 2.0.8 on 2018-10-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20181007_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
    ]
